version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongocontainer
    ports:
      - 27017:27017
  studentapp:
    image: studentimg
    ports:
      - 8080:8080
    links:
      - mongodb
